default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= (ENV.fetch("PG_TIMEOUT_IN_SECONDS") { 3 }).seconds %>

development:
  database: <%= ENV.fetch("PG_DATABASE_NAME") { "code_fund_ads_development" } %>
  <<: *default

test:
  <<: *default
  database: code_fund_ads_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
