# IMPORTANT: All application enums should be defined in this file
#
# They will be made available to the application via: config/initializers/enums.rb
# ...and will be exposed uner the ENUMS module
#
# NOTE: Entries in this file can be either key/value or a simple list
#
# Examples
#
#   RATINGS:
#     gold: happy
#     silver: satisfied
#     bronze: sad
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::RATINGS::GOLD        # happy
#   pry>ENUMS::RATINGS::HAPPY       # gold
#   pry>ENUMS::RATINGS::SILVER      # satisfied
#   pry>ENUMS::RATINGS::SATISFIED   # silver
#   pry>ENUMS::RATINGS::BRONZE      # sad
#   pry>ENUMS::RATINGS::SAD         # bronze
#
#   ENUMs also supports the following helper methods
#
#   pry>ENUMS::RATINGS.keys             # [gold, silver, bronze]
#   pry>ENUMS::RATINGS.values           # [happy, satisfied, sad]
#   pry>ENUMS::RATINGS.happy? :gold     # true
#   pry>ENUMS::RATINGS.happy? :bronze   # false
#   pry>ENUMS::RATINGS["happy"]         # gold
#   pry>ENUMS::RATINGS["gold"]          # happy
#
#   ----------------------------------------------------------------------------
#
#   USER_ROLES:
#     - administrator
#     - advertiser
#     - publisher
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::USER_ROLES::ADMINISTRATOR # administrator
#   pry>ENUMS::USER_ROLES::ADVERTISER    # advertiser
#   pry>ENUMS::USER_ROLES::PUBLISHER     # publisher
#
#   pry>ENUMS::USER_ROLES.keys                          # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.values                        # [administrator, advertiser, publisher]
#   pry>ENUMS::USER_ROLES.administrator? :administrator # true
#   pry>ENUMS::USER_ROLES.administrator? :publisher     # false
#   pry>ENUMS::USER_ROLES["administrator"]              # administrator
#
#   ----------------------------------------------------------------------------
#
#   CAMPAIGN_STATUSES:
#     1: pending
#     2: active
#     3: archived
#
#   The YAML above will be converted to the following enums
#
#   pry>ENUMS::CAMPAIGN_STATUSES::PENDING    # 1
#   pry>ENUMS::CAMPAIGN_STATUSES::ACTIVE     # 2
#   pry>ENUMS::CAMPAIGN_STATUSES::ARCHIVED   # 3
#
#   pry>ENUMS::CAMPAIGN_STATUSES.keys        # [1, 2, 3]
#   pry>ENUMS::CAMPAIGN_STATUSES.values      # [pending, active, archived]
#   pry>ENUMS::CAMPAIGN_STATUSES.pending? 1  # true
#   pry>ENUMS::CAMPAIGN_STATUSES.pending? 2  # false
#   pry>ENUMS::CAMPAIGN_STATUSES["active"]   # 2
#   pry>ENUMS::CAMPAIGN_STATUSES[2]          # active
#

APPLICANT_STATUSES:
  - pending
  - accepted
  - rejected

APPLICANT_ROLES:
  - advertiser
  - publisher

USER_ROLES:
  - administrator
  - advertiser
  - publisher

CAMPAIGN_STATUSES:
  - pending
  - active
  - archived

CAMPAIGN_STATUS_COLORS:
  pending: warning
  active: success
  archived: muted

PROPERTY_TYPES:
  - website
  - repository
  - newsletter

PROPERTY_STATUSES:
  - pending
  - active
  - rejected
  - archived
  - blacklisted

PROPERTY_STATUS_COLORS:
  pending: warning
  active: success
  rejected: danger
  archived: muted
  blacklisted: dark

IMAGE_FORMATS:
  - small
  - large
  - wide

IMAGE_CONTENT_TYPES:
  - image/gif
  - image/jpeg
  - image/png

IMPRESSION_CODES:
  - ok
  - property_inactive
  - impression_count_exceeded
  - no_possible_ads

RESERVED_ORGANIZATION_NAMES:
  - codefund

ORGANIZATION_TRANSACTION_TYPES:
  - debit
  - credit

ORGANIZATION_SEARCH_DIRECTIONS:
  - positive
  - negative
  - zero

# SEE: https://dev.maxmind.com/geoip/legacy/codes/iso3166/
COUNTRIES:
  EASTERN_AFRICA:
    BI: Burundi
    KM: Comoros
    DJ: Djibouti
    ER: Eritrea
    ET: Ethiopia
    KE: Kenya
    MG: Madagascar
    MW: Malawi
    MU: Mauritius
    YT: Mayotte
    MZ: Mozambique
    RE: Reunion
    RW: Rwanda
    SC: Seychelles
    SO: Somalia
    TZ: Tanzania, United Republic of
    UG: Uganda
    ZM: Zambia
    ZW: Zimbabwe
  MIDDLE_AFRICA:
    AO: Angola
    CM: Cameroon
    CF: Central African Republic
    TD: Chad
    CG: Congo
    CD: Congo, The Democratic Republic of the
    GQ: Equatorial Guinea
    GA: Gabon
    ST: Sao Tome and Principe
  NORTHERN_AFRICA:
    DZ: Algeria
    EG: Egypt
    LY: Libyan Arab Jamahiriya
    MA: Morocco
    SS: South Sudan
    SD: Sudan
    TN: Tunisia
    EH: Western Sahara
  SOUTHERN_AFRICA:
    BW: Botswana
    LS: Lesotho
    NA: Namibia
    ZA: South Africa
    SZ: Swaziland
  WESTERN_AFRICA:
    BJ: Benin
    BF: Burkina Faso
    CV: Cape Verde
    CI: Cote d'Ivoire
    GM: Gambia
    GH: Ghana
    GN: Guinea
    GW: Guinea-Bissau
    LR: Liberia
    ML: Mali
    MR: Mauritania
    NE: Niger
    NG: Nigeria
    SH: Saint Helena
    SN: Senegal
    SL: Sierra Leone
    TG: Togo
  ASIA:
  CENTRAL_AMERICA:
    BZ: Belize
    CR: Costa Rica
    SV: El Salvador
    GT: Guatemala
    HN: Honduras
    MX: Mexico
    NI: Nicaragua
    PA: Panama
  EASTERN_EUROPE:
  MIDDLE_EAST:
  NORTH_AMERICA:
    BM: Bermuda
    CA: Canada
    GL: Greenland
    PM: Saint Pierre and Miquelon
    US: United States
  OCEANIA:
  SOUTH_AMERICA:
    AR: Argentina
    BO: Bolivia
    BR: Brazil
    CL: Chile
    CO: Colombia
    EC: Ecuador
    FK: Falkland Islands (Malvinas)
    GF: French Guiana
    GY: Guyana
    PY: Paraguay
    PE: Peru
    SR: Suriname
    UY: Uruguay
    VE: Venezuela
  THE_CARIBBEAN:
    AI: Anguilla
    AG: Antigua and Barbuda
    AW: Aruba
    BS: Bahamas
    BB: Barbados
    BQ: Bonaire, Saint Eustatius and Saba
    VG: Virgin Islands, British
    KY: Cayman Islands
    CU: Cuba
    CW: Curacao
    DM: Dominica
    DO: Dominican Republic
    GD: Grenada
    GP: Guadeloupe
    HT: Haiti
    JM: Jamaica
    MQ: Martinique
    MS: Montserrat
    PR: Puerto Rico
    BL: Saint Barthelemy
    KN: Saint Kitts and Nevis
    LC: Saint Lucia
    MF: Saint Martin
    VC: Saint Vincent and the Grenadines
    SX: Sint Maarten
    TT: Trinidad and Tobago
    TC: Turks and Caicos Islands
    VI: Virgin Islands, U.S.



  AF: Afghanistan
  AX: Aland Islands
  AL: Albania
  AS: American Samoa
  AD: Andorra
  AQ: Antarctica
  AM: Armenia
  AP: Asia/Pacific Region
  AU: Australia
  AT: Austria
  AZ: Azerbaijan
  BH: Bahrain
  BD: Bangladesh
  BY: Belarus
  BE: Belgium
  BT: Bhutan
  BA: Bosnia and Herzegovina
  BV: Bouvet Island
  IO: British Indian Ocean Territory
  BN: Brunei Darussalam
  BG: Bulgaria
  
  KH: Cambodia
  CN: China
  CX: Christmas Island
  CC: Cocos (Keeling) Islands
  
  CK: Cook Islands
  HR: Croatia
  CY: Cyprus
  CZ: Czech Republic
  DK: Denmark
  EE: Estonia
  EU: Europe
  FO: Faroe Islands
  FJ: Fiji
  FI: Finland
  FR: France
  PF: French Polynesia
  TF: French Southern Territories
  GE: Georgia
  DE: Germany
  GI: Gibraltar
  GR: Greece
  GU: Guam
  GG: Guernsey
  HM: Heard Island and McDonald Islands
  VA: Holy See (Vatican City State)
  HK: Hong Kong
  HU: Hungary
  IS: Iceland
  IN: India
  ID: Indonesia
  IR: Iran, Islamic Republic of
  IQ: Iraq
  IE: Ireland
  IM: Isle of Man
  IL: Israel
  IT: Italy
  JP: Japan
  JE: Jersey
  JO: Jordan
  KZ: Kazakhstan
  KI: Kiribati
  KP: Korea, Democratic People's Republic of
  KR: Korea, Republic of
  KW: Kuwait
  KG: Kyrgyzstan
  LA: Lao People's Democratic Republic
  LV: Latvia
  LB: Lebanon
  LI: Liechtenstein
  LT: Lithuania
  LU: Luxembourg
  MO: Macao
  MK: Macedonia
  MY: Malaysia
  MV: Maldives
  MT: Malta
  MH: Marshall Islands
  FM: Micronesia, Federated States of
  MD: Moldova, Republic of
  MC: Monaco
  MN: Mongolia
  ME: Montenegro
  MM: Myanmar
  NR: Nauru
  NP: Nepal
  NL: Netherlands
  NC: New Caledonia
  NZ: New Zealand
  NU: Niue
  NF: Norfolk Island
  MP: Northern Mariana Islands
  "NO": Norway
  OM: Oman
  PK: Pakistan
  PW: Palau
  PS: Palestinian Territory
  PG: Papua New Guinea
  PH: Philippines
  PN: Pitcairn
  PL: Poland
  PT: Portugal
  QA: Qatar
  RO: Romania
  RU: Russian Federation
  WS: Samoa
  SM: San Marino
  SA: Saudi Arabia
  RS: Serbia
  SG: Singapore
  SK: Slovakia
  SI: Slovenia
  SB: Solomon Islands
  GS: South Georgia and the South Sandwich Islands
  ES: Spain
  LK: Sri Lanka
  SJ: Svalbard and Jan Mayen
  SE: Sweden
  CH: Switzerland
  SY: Syrian Arab Republic
  TW: Taiwan
  TJ: Tajikistan
  TH: Thailand
  TL: Timor-Leste
  TK: Tokelau
  TO: Tonga
  TR: Turkey
  TM: Turkmenistan
  TV: Tuvalu
  UA: Ukraine
  AE: United Arab Emirates
  GB: United Kingdom
  UM: United States Minor Outlying Islands
  UZ: Uzbekistan
  VU: Vanuatu
  VN: Vietnam
  WF: Wallis and Futuna
  YE: Yemen

# SEE: https://www.msci.com/market-classification
DEVELOPED_MARKET_COUNTRIES:
  AU: Australia
  AT: Austria
  BE: Belgium
  CA: Canada
  DK: Denmark
  FI: Finland
  FR: France
  DE: Germany
  HK: Hong Kong
  IE: Ireland
  IL: Israel
  IT: Italy
  JP: Japan
  NL: Netherlands
  NZ: New Zealand
  "NO": Norway
  PT: Portugal
  SG: Singapore
  ES: Spain
  SE: Sweden
  CH: Switzerland
  GB: United Kingdom
  US: United States

EMERGING_MARKET_COUNTRIES:
  BR: Brazil
  CL: Chile
  CN: China
  CO: Colombia
  CZ: Czech Republic
  EG: Egypt
  GR: Greece
  HU: Hungary
  IN: India
  ID: Indonesia
  KR: Korea, Republic of
  MY: Malaysia
  MX: Mexico
  PK: Pakistan
  PE: Peru
  PH: Philippines
  PL: Poland
  QA: Qatar
  RU: Russian Federation
  ZA: South Africa
  TW: Taiwan
  TH: Thailand
  TR: Turkey
  AE: United Arab Emirates

LANGUAGES:
  - Albanian
  - Armenian
  - Azeri
  - Belarusian
  - Bosnian
  - Bulgarian
  - Chinese
  - Croatian
  - Czech
  - Danish
  - Divehi
  - Dutch
  - English
  - Estonian
  - FYRO Macedonian
  - Faroese
  - Farsi
  - Finnish
  - French
  - Galician
  - Georgian
  - German
  - Greek
  - Hebrew
  - Hindi
  - Hungarian
  - Icelandic
  - Indonesian
  - Italian
  - Japanese
  - Kazakh
  - Korean
  - Kyrgyz
  - Latvian
  - Lithuanian
  - Malay
  - Maltese
  - Maori
  - Mongolian
  - Norwegian
  - Pashto
  - Polish
  - Portuguese
  - Romanian
  - Russian
  - Serbian
  - Slovak
  - Slovenian
  - Spanish
  - Swahili
  - Swedish
  - Syriac
  - Tagalog
  - Thai
  - Turkish
  - Ukrainian
  - Urdu
  - Uzbek
  - Vietnamese
  - Zulu

KEYWORDS:
  # topics
  - Android Development
  - Backend Services
  - Blockchain
  - CSS & Design
  - Computer Science
  - Database
  - Dev Ops
  - Docker
  - Frontend Concepts
  - Frontend Frameworks & Tools
  - Frontend Workflow & Tooling
  - Game Development
  - Git
  - HTML5
  - Hybrid & Mobile Web
  - IOS Development
  - Languages & Frameworks
  - React
  - Resources
  - Shell

  # programming languages
  - ABAP
  - Ada
  - Alice
  - Apex
  - Assembly language
  - Awk
  - Bash
  - C
  - C#
  - C++
  - COBOL
  - D
  - Dart
  - Delphi/Object Pascal
  - Erlang
  - F#
  - Fortran
  - Go
  - Groovy
  - Haskell
  - Java
  - JavaScript
  - Julia
  - LabVIEW
  - Ladder Logic
  - Lisp
  - Logo
  - Lua
  - MATLAB
  - MQL4
  - Objective-C
  - Other
  - PHP
  - PL/SQL
  - Perl
  - Prolog
  - Python
  - Q
  - R
  - RPG (OS/400)
  - Ruby
  - Rust
  - SAS
  - Scala
  - Scheme
  - Scratch
  - Swift
  - Transact-SQL
  - VHDL
  - Visual Basic
  - Visual Basic .NET
