# SEE: https://dev.maxmind.com/geoip/legacy/codes/iso3166/
countries:
  #A1: Anonymous Proxy
  #A2: Satellite Provider
  #O1: Other Country
  AF: Afghanistan
  AX: Aland Islands
  AL: Albania
  DZ: Algeria
  AS: American Samoa
  AD: Andorra
  AO: Angola
  AI: Anguilla
  AQ: Antarctica
  AG: Antigua and Barbuda
  AR: Argentina
  AM: Armenia
  AW: Aruba
  AP: Asia/Pacific Region
  AU: Australia
  AT: Austria
  AZ: Azerbaijan
  BS: Bahamas
  BH: Bahrain
  BD: Bangladesh
  BB: Barbados
  BY: Belarus
  BE: Belgium
  BZ: Belize
  BJ: Benin
  BM: Bermuda
  BT: Bhutan
  BO: Bolivia
  BQ: Bonaire, Saint Eustatius and Saba
  BA: Bosnia and Herzegovina
  BW: Botswana
  BV: Bouvet Island
  BR: Brazil
  IO: British Indian Ocean Territory
  BN: Brunei Darussalam
  BG: Bulgaria
  BF: Burkina Faso
  BI: Burundi
  KH: Cambodia
  CM: Cameroon
  CA: Canada
  CV: Cape Verde
  KY: Cayman Islands
  CF: Central African Republic
  TD: Chad
  CL: Chile
  CN: China
  CX: Christmas Island
  CC: Cocos (Keeling) Islands
  CO: Colombia
  KM: Comoros
  CG: Congo
  CD: Congo, The Democratic Republic of the
  CK: Cook Islands
  CR: Costa Rica
  CI: Cote d'Ivoire
  HR: Croatia
  CU: Cuba
  CW: Curacao
  CY: Cyprus
  CZ: Czech Republic
  DK: Denmark
  DJ: Djibouti
  DM: Dominica
  DO: Dominican Republic
  EC: Ecuador
  EG: Egypt
  SV: El Salvador
  GQ: Equatorial Guinea
  ER: Eritrea
  EE: Estonia
  ET: Ethiopia
  EU: Europe
  FK: Falkland Islands (Malvinas)
  FO: Faroe Islands
  FJ: Fiji
  FI: Finland
  FR: France
  GF: French Guiana
  PF: French Polynesia
  TF: French Southern Territories
  GA: Gabon
  GM: Gambia
  GE: Georgia
  DE: Germany
  GH: Ghana
  GI: Gibraltar
  GR: Greece
  GL: Greenland
  GD: Grenada
  GP: Guadeloupe
  GU: Guam
  GT: Guatemala
  GG: Guernsey
  GN: Guinea
  GW: Guinea-Bissau
  GY: Guyana
  HT: Haiti
  HM: Heard Island and McDonald Islands
  VA: Holy See (Vatican City State)
  HN: Honduras
  HK: Hong Kong
  HU: Hungary
  IS: Iceland
  IN: India
  ID: Indonesia
  IR: Iran, Islamic Republic of
  IQ: Iraq
  IE: Ireland
  IM: Isle of Man
  IL: Israel
  IT: Italy
  JM: Jamaica
  JP: Japan
  JE: Jersey
  JO: Jordan
  KZ: Kazakhstan
  KE: Kenya
  KI: Kiribati
  KP: Korea, Democratic People's Republic of
  KR: Korea, Republic of
  KW: Kuwait
  KG: Kyrgyzstan
  LA: Lao People's Democratic Republic
  LV: Latvia
  LB: Lebanon
  LS: Lesotho
  LR: Liberia
  LY: Libyan Arab Jamahiriya
  LI: Liechtenstein
  LT: Lithuania
  LU: Luxembourg
  MO: Macao
  MK: Macedonia
  MG: Madagascar
  MW: Malawi
  MY: Malaysia
  MV: Maldives
  ML: Mali
  MT: Malta
  MH: Marshall Islands
  MQ: Martinique
  MR: Mauritania
  MU: Mauritius
  YT: Mayotte
  MX: Mexico
  FM: Micronesia, Federated States of
  MD: Moldova, Republic of
  MC: Monaco
  MN: Mongolia
  ME: Montenegro
  MS: Montserrat
  MA: Morocco
  MZ: Mozambique
  MM: Myanmar
  NA: Namibia
  NR: Nauru
  NP: Nepal
  NL: Netherlands
  NC: New Caledonia
  NZ: New Zealand
  NI: Nicaragua
  NE: Niger
  NG: Nigeria
  NU: Niue
  NF: Norfolk Island
  MP: Northern Mariana Islands
  "NO": Norway
  OM: Oman
  PK: Pakistan
  PW: Palau
  PS: Palestinian Territory
  PA: Panama
  PG: Papua New Guinea
  PY: Paraguay
  PE: Peru
  PH: Philippines
  PN: Pitcairn
  PL: Poland
  PT: Portugal
  PR: Puerto Rico
  QA: Qatar
  RE: Reunion
  RO: Romania
  RU: Russian Federation
  RW: Rwanda
  BL: Saint Barthelemy
  SH: Saint Helena
  KN: Saint Kitts and Nevis
  LC: Saint Lucia
  MF: Saint Martin
  PM: Saint Pierre and Miquelon
  VC: Saint Vincent and the Grenadines
  WS: Samoa
  SM: San Marino
  ST: Sao Tome and Principe
  SA: Saudi Arabia
  SN: Senegal
  RS: Serbia
  SC: Seychelles
  SL: Sierra Leone
  SG: Singapore
  SX: Sint Maarten
  SK: Slovakia
  SI: Slovenia
  SB: Solomon Islands
  SO: Somalia
  ZA: South Africa
  GS: South Georgia and the South Sandwich Islands
  SS: South Sudan
  ES: Spain
  LK: Sri Lanka
  SD: Sudan
  SR: Suriname
  SJ: Svalbard and Jan Mayen
  SZ: Swaziland
  SE: Sweden
  CH: Switzerland
  SY: Syrian Arab Republic
  TW: Taiwan
  TJ: Tajikistan
  TZ: Tanzania, United Republic of
  TH: Thailand
  TL: Timor-Leste
  TG: Togo
  TK: Tokelau
  TO: Tonga
  TT: Trinidad and Tobago
  TN: Tunisia
  TR: Turkey
  TM: Turkmenistan
  TC: Turks and Caicos Islands
  TV: Tuvalu
  UG: Uganda
  UA: Ukraine
  AE: United Arab Emirates
  GB: United Kingdom
  US: United States
  UM: United States Minor Outlying Islands
  UY: Uruguay
  UZ: Uzbekistan
  VU: Vanuatu
  VE: Venezuela
  VN: Vietnam
  VG: Virgin Islands, British
  VI: Virgin Islands, U.S.
  WF: Wallis and Futuna
  EH: Western Sahara
  YE: Yemen
  ZM: Zambia
  ZW: Zimbabwe

# SEE: https://www.msci.com/market-classification
developed_markets:
  AU: Australia
  AT: Austria
  BE: Belgium
  CA: Canada
  DK: Denmark
  FI: Finland
  FR: France
  DE: Germany
  HK: Hong Kong
  IE: Ireland
  IL: Israel
  IT: Italy
  JP: Japan
  NL: Netherlands
  NZ: New Zealand
  "NO": Norway
  PT: Portugal
  SG: Singapore
  ES: Spain
  SE: Sweden
  CH: Switzerland
  GB: United Kingdom
  US: United States

emerging_markets:
  BR: Brazil
  CL: Chile
  CN: China
  CO: Colombia
  CZ: Czech Republic
  EG: Egypt
  GR: Greece
  HU: Hungary
  IN: India
  ID: Indonesia
  KR: Korea, Republic of
  MY: Malaysia
  MX: Mexico
  PK: Pakistan
  PE: Peru
  PH: Philippines
  PL: Poland
  QA: Qatar
  RU: Russian Federation
  ZA: South Africa
  TW: Taiwan
  TH: Thailand
  TR: Turkey
  AE: United Arab Emirates

languages:
  albanian: Albanian
  armenian: Armenian
  azeri: Azeri
  belarusian: Belarusian
  bosnian: Bosnian
  bulgarian: Bulgarian
  chinese: Chinese
  croatian: Croatian
  czech: Czech
  danish: Danish
  divehi: Divehi
  dutch: Dutch
  english: English
  estonian: Estonian
  fyro macedonian: FYRO Macedonian
  faroese: Faroese
  farsi: Farsi
  finnish: Finnish
  french: French
  galician: Galician
  georgian: Georgian
  german: German
  greek: Greek
  hebrew: Hebrew
  hindi: Hindi
  hungarian: Hungarian
  icelandic: Icelandic
  indonesian: Indonesian
  italian: Italian
  japanese: Japanese
  kazakh: Kazakh
  korean: Korean
  kyrgyz: Kyrgyz
  latvian: Latvian
  lithuanian: Lithuanian
  malay: Malay
  maltese: Maltese
  maori: Maori
  mongolian: Mongolian
  norwegian: Norwegian
  pashto: Pashto
  polish: Polish
  portuguese: Portuguese
  romanian: Romanian
  russian: Russian
  serbian: Serbian
  slovak: Slovak
  slovenian: Slovenian
  spanish: Spanish
  swahili: Swahili
  swedish: Swedish
  syriac: Syriac
  tagalog: Tagalog
  thai: Thai
  turkish: Turkish
  ukrainian: Ukrainian
  urdu: Urdu
  uzbek: Uzbek
  vietnamese: Vietnamese
  zulu: Zulu

programming_languages:
  abap: ABAP
  ada: Ada
  alice: Alice
  apex: Apex
  assembly: Assembly language
  awk: Awk
  bash: Bash
  c: C
  c_sharp: C#
  c++: C++
  cobol: COBOL
  d: D
  dart: Dart
  delphi: Delphi/Object Pascal
  erlang: Erlang
  f_sharp: F#
  fortran: Fortran
  go: Go
  groovy: Groovy
  haskell: Haskell
  java: Java
  javascript: JavaScript
  julia: Julia
  labview: LabVIEW
  ladder_logic: Ladder Logic
  lisp: Lisp
  logo: Logo
  lua: Lua
  matlab: MATLAB
  mql4: MQL4
  objective_c: Objective-C
  other: Other
  php: PHP
  pl_sql: PL/SQL
  perl: Perl
  prolog: Prolog
  python: Python
  q: Q
  r: R
  rpg_os_400: RPG (OS/400)
  ruby: Ruby
  rust: Rust
  sas: SAS
  scala: Scala
  scheme: Scheme
  scratch: Scratch
  swift: Swift
  transact_sql: Transact-SQL
  vhdl: VHDL
  visual_basic: Visual Basic
  visual_basic_net: Visual Basic .NET

topic_categories:
  android_development: Android Development
  backend_services: Backend Services
  blockchain: Blockchain
  css_design: CSS & Design
  computer_science: Computer Science
  database: Database
  devops: Dev Ops
  docker: Docker
  frontend_concepts: Frontend Concepts
  frontend_frameworks_tools: Frontend Frameworks & Tools
  frontend_workflow_tooling: Frontend Workflow & Tooling
  game_development: Game Development
  git: Git
  html5: HTML5
  hybrid_mobile_web: Hybrid & Mobile Web
  ios_development: IOS Development
  languages_frameworks: Languages & Frameworks
  react: React
  resources: Resources
  shell: Shell
