common: &defaults
  monitor: true
  ignore:
    - '/okcomputer'
    - '/okcomputer.json'
    - '/okcomputer/all'
    - '/okcomputer/all.json'

development:
  monitor: false

production:
  <<: *defaults
